//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionSteel.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABOUTUS
    {
        public System.Guid ID { get; set; }
        public string WHOAREWE_TR { get; set; }
        public string WHOAREWE_ENG { get; set; }
        public string MISSION_TR { get; set; }
        public string MISSION_ENG { get; set; }
        public string VISION_TR { get; set; }
        public string VISION_ENG { get; set; }
        public int PRODUCT { get; set; }
        public int CLIENT { get; set; }
        public int COMPANY { get; set; }
    }
}
