//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionSteel.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public System.Guid ID { get; set; }
        public string ADDRESS { get; set; }
        public string MAIL { get; set; }
        public string TELEPHONE { get; set; }
        public string FACEBOOK { get; set; }
        public string TWITTER { get; set; }
        public string LINKEDIN { get; set; }
        public string INSTAGRAM { get; set; }
    }
}
