//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionSteel.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL
    {
        public System.Guid ID { get; set; }
        public string NAME { get; set; }
        public string MAIL1 { get; set; }
        public string SUBJECT { get; set; }
        public string MESSAGE { get; set; }
        public bool ISREAD { get; set; }
    }
}
