//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionSteel.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETER
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string VALUE { get; set; }
        public string DESCP { get; set; }
    }
}
