//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionSteel.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLIDER
    {
        public int ID { get; set; }
        public string MAINTEXT_TR { get; set; }
        public string MAINTEXT_ENG { get; set; }
        public string TITLE_TR { get; set; }
        public string TITLE_ENG { get; set; }
        public string IMAGE { get; set; }
        public int SORT { get; set; }
    }
}
